services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
      - "443:443"
    container_name: nginx-proxy
    volumes:
      - ./nginx/log:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/htpasswd/:/etc/nginx/htpasswd/:ro
      - ./nginx/blocklist.conf:/etc/nginx/blocklist.conf:ro
    networks:
      - shared-network

networks:
  shared-network:
    external: true